---
- name: "Install apt-transport-https"
  package:
    pkg: "{{ install_apt_transport_https_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  tags:
    - "apt-transport-https"
